#!/usr/bin/env python3
"""Send a signed Linear-compatible webhook payload to a bridge endpoint."""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import sys
import time
import urllib.error
import urllib.request
import uuid
from typing import Any


def make_issue_data(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "id": args.issue_id,
        "identifier": args.issue_identifier,
        "title": args.title,
        "description": args.description,
        "url": args.issue_url,
        "priority": args.priority,
        "state": {"name": args.state},
        "assignee": {"name": args.assignee},
        "teamId": args.team_id,
    }


def make_comment_data(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "id": args.comment_id,
        "body": args.comment_body,
        "issue": {
            "id": args.issue_id,
            "identifier": args.issue_identifier,
            "title": args.title,
            "url": args.issue_url,
        },
        "parent": {"id": args.issue_id, "type": "Issue"},
    }


def build_payload(args: argparse.Namespace) -> dict[str, Any]:
    resource_type, action = args.event.split(":", 1)
    payload = {
        "action": action,
        "type": resource_type,
        "createdAt": args.created_at,
        "organizationId": args.organization_id,
        "organizationSlug": args.organization_slug,
        "webhookTimestamp": args.webhook_timestamp,
        "actor": {
            "id": args.actor_id,
            "name": args.actor_name,
            "email": args.actor_email,
        },
    }
    payload["data"] = make_comment_data(args) if resource_type == "Comment" else make_issue_data(args)
    return payload


def sign(secret: str, raw_body: bytes) -> str:
    return hmac.new(secret.encode("utf-8"), raw_body, hashlib.sha256).hexdigest()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Send a signed test webhook that matches Linear's HMAC + header rules."
    )
    parser.add_argument("--url", required=True, help="Bridge endpoint URL.")
    parser.add_argument("--secret", required=True, help="Linear webhook secret.")
    parser.add_argument(
        "--event",
        default="Comment:created",
        choices=("Issue:created", "Issue:updated", "Issue:deleted", "Comment:created"),
        help="Linear event type to generate.",
    )
    parser.add_argument("--organization-id", default="org_test_123")
    parser.add_argument("--organization-slug", default="test-workspace")
    parser.add_argument("--team-id", default="team_test_123")
    parser.add_argument("--issue-id", default="issue_test_123")
    parser.add_argument("--issue-identifier", default="WHO-210")
    parser.add_argument("--issue-url", default="https://linear.app/test/issue/WHO-210")
    parser.add_argument("--title", default="[Test] Linear webhook bridge smoke test")
    parser.add_argument("--description", default="Manual webhook test generated by send_test_webhook.py")
    parser.add_argument("--priority", type=int, default=3)
    parser.add_argument("--state", default="Todo")
    parser.add_argument("--assignee", default="Hermes Agent")
    parser.add_argument("--comment-id", default="comment_test_123")
    parser.add_argument("--comment-body", default="@hermesagent 請回覆這則 webhook 測試。")
    parser.add_argument("--actor-id", default="actor_test_123")
    parser.add_argument("--actor-name", default="Webhook Tester")
    parser.add_argument("--actor-email", default="tester@example.com")
    parser.add_argument(
        "--delivery-id",
        default=str(uuid.uuid4()),
        help="Override the Linear-Delivery UUID for replay tests.",
    )
    parser.add_argument(
        "--created-at",
        default=time.strftime("%Y-%m-%dT%H:%M:%S.000Z", time.gmtime()),
        help="createdAt timestamp included in the payload.",
    )
    parser.add_argument(
        "--webhook-timestamp",
        type=int,
        default=int(time.time() * 1000),
        help="webhookTimestamp in Unix ms. Defaults to now.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=10.0,
        help="HTTP timeout in seconds.",
    )
    parser.add_argument(
        "--raw-body-file",
        help="Optional path to write the exact raw request body bytes used for signing.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the request without sending it.",
    )
    parser.add_argument(
        "--pretty",
        action="store_true",
        help="Pretty-print payload JSON output.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    payload = build_payload(args)
    raw_body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    signature = sign(args.secret, raw_body)
    if args.raw_body_file:
        with open(args.raw_body_file, "wb") as fh:
            fh.write(raw_body)
    resource_type, _ = args.event.split(":", 1)
    headers = {
        "Content-Type": "application/json",
        "Linear-Signature": signature,
        "Linear-Delivery": args.delivery_id,
        "Linear-Event": resource_type,
    }

    request_summary = {
        "url": args.url,
        "headers": headers,
        "payload": payload,
    }
    json.dump(request_summary, sys.stdout, ensure_ascii=False, indent=2 if args.pretty else None)
    sys.stdout.write("\n")

    if args.dry_run:
        return 0

    request = urllib.request.Request(args.url, data=raw_body, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(request, timeout=args.timeout) as response:
            response_body = response.read().decode("utf-8", errors="replace")
            result = {
                "status": response.status,
                "reason": response.reason,
                "response_body": response_body,
            }
            json.dump(result, sys.stdout, ensure_ascii=False, indent=2 if args.pretty else None)
            sys.stdout.write("\n")
            return 0
    except urllib.error.HTTPError as exc:
        error_body = exc.read().decode("utf-8", errors="replace")
        result = {
            "status": exc.code,
            "reason": exc.reason,
            "response_body": error_body,
        }
        json.dump(result, sys.stdout, ensure_ascii=False, indent=2 if args.pretty else None)
        sys.stdout.write("\n")
        return 1
    except urllib.error.URLError as exc:
        print(json.dumps({"error": str(exc.reason)}, ensure_ascii=False))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
